name: "Cachix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v10
      with:
        name: lom
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#alacritty-ligatures -L
    #- run: nix build .#aw-watcher-afk -L
    #- run: nix build .#aw-watcher-window -L
    #- run: nix build .#aw-webui -L
    # - run: nix build .#aw-qt -L
    #- run: nix build .#aw-core -L
    #- run: nix build .#aw-server-rust -L
    - run: nix build .#lucky-commit -L
    - run: nix build .#cliscord -L
    - run: nix build .#st-patches -L

    # - run: nix build .#neovim-nightly -L
    # - run: nix build .#nixosConfigurations.pain.config.system.build.toplevel -L
